name: Deploy Flask App to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Create Artifact Registry repository
        run: |
          gcloud artifacts repositories create voicemail-webhook \
            --repository-format=docker \
            --location=us-central1 \
            --description="Docker repository" || echo "Repository may already exist"

      - name: Authenticate Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/voicemail-webhook/voicemail-webhook:${{ github.sha }} .

      - name: Push Docker image
        run: docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/voicemail-webhook/voicemail-webhook:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy voicemail-webhook \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/voicemail-webhook/voicemail-webhook:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
            --set-env-vars company_id=${{ secrets.COMPANY_ID }}, manage_url=${{ secrets.MANAGE_URL }}, client_id=${{ secrets.CLIENT_ID }}, public_key=${{ secrets.PUBLIC_KEY }}, private_key=${{ secrets.PRIVATE_KEY }}
