name: Deploy Flask App to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'beta'

      - name: Build Docker image
        run: docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/voicemail-webhook/voicemail-webhook .

      - name: Push Docker image
        run: docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/voicemail-webhook/voicemail-webhook

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy voicemail-webhook \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/voicemail-webhook/voicemail-webhook \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
